i686-elf-as   -o boot.o boot.s
boot.s: Assembler messages:
boot.s:49: Error: no such instruction: `dd 0'
boot.s:50: Error: no such instruction: `dd 0'
boot.s:52: Error: no such instruction: `dw 0xFFFF'
boot.s:53: Error: no such instruction: `dw 0x0000'
boot.s:54: Error: no such instruction: `db 0x00'
boot.s:55: Error: no such instruction: `db 0x9A'
boot.s:56: Error: no such instruction: `db 0xCF'
boot.s:57: Error: no such instruction: `db 0x00'
boot.s:59: Error: no such instruction: `dw 0xFFFF'
boot.s:60: Error: no such instruction: `dw 0x0000'
boot.s:61: Error: no such instruction: `db 0x00'
boot.s:62: Error: no such instruction: `db 0x92'
boot.s:63: Error: no such instruction: `db 0xCF'
boot.s:64: Error: no such instruction: `db 0x00'
boot.s:66: Error: no such instruction: `dw 0xFFFF'
boot.s:67: Error: no such instruction: `dw 0x0000'
boot.s:68: Error: no such instruction: `db 0x00'
boot.s:69: Error: no such instruction: `db 0x92'
boot.s:70: Error: no such instruction: `db 0xCF'
boot.s:71: Error: no such instruction: `db 0x00'
boot.s:72: Error: no such instruction: `dw 0xFFFF'
boot.s:73: Error: no such instruction: `dw 0x0000'
boot.s:74: Error: no such instruction: `db 0x00'
boot.s:75: Error: no such instruction: `db 0x9A'
boot.s:76: Error: no such instruction: `db 0xCF'
boot.s:77: Error: no such instruction: `db 0x00'
boot.s:79: Error: no such instruction: `dw 0xFFFF'
boot.s:80: Error: no such instruction: `dw 0x0000'
boot.s:81: Error: no such instruction: `db 0x00'
boot.s:82: Error: no such instruction: `db 0x92'
boot.s:83: Error: no such instruction: `db 0xCF'
boot.s:84: Error: no such instruction: `db 0x00'
boot.s:86: Error: no such instruction: `dw 0xFFFF'
boot.s:87: Error: no such instruction: `dw 0x0000'
boot.s:88: Error: no such instruction: `db 0x00'
boot.s:89: Error: no such instruction: `db 0x92'
boot.s:90: Error: no such instruction: `db 0xCF'
boot.s:91: Error: no such instruction: `db 0x00'
boot.s:95: Error: no such instruction: `dw gdt_end - gdt_start - 1'
boot.s:96: Error: no such instruction: `dd gdt_start'
boot.s:106: Error: .space, .nops or .fill specifies non-absolute value
make: *** [<builtin>: boot.o] Error 1


